---
abstract: 'Add module directories of a project into @INC'
author:
  - 'Kentaro Kuribayashi, <kentarok@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Project-Libs
no_index:
  directory:
    - inc
    - t
requires:
  FindBin::libs: 0
  perl: 5.8.1
resources:
  license: http://opensource.org/licenses/mit-license.php
  repository: git://github.com/kentaro/perl-project-libs.git
version: 0.01
